openapi: 3.0.1
info:
  description: Employee Management API
  version: 1.0.0-oas3
  title: EPM-API
  
paths:
  /employees/add:
    post:
      requestBody:
        description: "[REQ] Ajout d'un employé"
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmployeeSalaried'
      responses:
        '201':
          description: "[201] Ajout réussi"
        '400':
          description: "[400] Données invalides"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidData'
                
  /employees/remove:
    post:
      requestBody:
        description: "[REQ] Suppression d'un employé"
        content:
          text/plain:
            schema:
              type: integer
              example: 123
      responses:
        '200':
          description: "[200] Suppression réussie"
        '400':
          description: "[400] Employé inexistant"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MissingEmployee'
                
  /timecard/add:
    post:
      requestBody:
        description: "[REQ] Envoi de timecard"
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostTimecard'
      responses:
        '200':
          description: "[200] Ajout de la timecard réussi"
        '400':
          description: "[400] Erreur de Timecard"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TimecardError'
      

components:
  schemas:
    EmployeeSalaried:
      type: object
      properties:
        empId:
          type: integer
          example: 123
        name:
          type: string
          example: "Jean-Claude"
        address:
          type: string
          example: "Rue de Mons"
        mail:
          type: string
          example: "jc@heh.be"
        monthlySalary:
          type: number
          example: 1500
          
    InvalidData:
      type: object
      properties:
        timestamp:
          type: string
          example: "2020-10-29T07:44:23.354+00:00"
        errors:
          type: array
          items: 
            type: string
            example: "e-mail invalide"
          
    MissingEmployee:
      type: object
      properties:
        empId:
          type: integer
          example: 123
        error:
          type: string
          example: "Employé inexistant"
          
    PostTimecard:
      type: object
      properties:
        empId:
          type: integer
          example: 123
        date:
          type: string
          example: "2020-10-29"
        hours:
          type: string
          example: "6h"
          
    TimecardError:
      type: object
      properties:
        empId:
          type: integer
          example: 123
        errors:
          type: array
          items:
            type: string
            example: "Cette timecard est incorrecte"